### ISSUE TITLE
3.0.4 not working with default nestjs tsconfig.json

### ISSUE THREAD

**Issue by markoffk** [Pop-Code/nestjs-console#145]
Hello. Thanks for your work!

Unfortunately, tsconfig.json needs to be adjusted to make app work with 3.x version of this library.
Following param should be added:
allowSyntheticDefaultImports:true

As long as default nestjs setup does not have such parameter set, some note should be added (IMO preferably TLDR) that this parameter should be set to true.

**Comment by tobeno** [comment]
Also just ran into this issue. Thought I add a couple more details to this.

This is the error:
```
node_modules/nestjs-console/dist/interfaces.d.ts:1:8 - error TS1259: Module '"node_modules/commander/typings/index"' can only be default-imported using the 'esModuleInterop' flag

1 import commander from 'commander';
         ~~~~~~~~~

  node_modules/commander/typings/index.d.ts:386:1
    386 export = commander;
        ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

Seems to be caused by the `import commander from 'commander';` in the interfaces.ts file. Should be easy to fix by just replacing this with `import * as commander from 'commander';`. Don't think there are any side-effects.

Since the `allowSyntheticDefaultImports` option is not really needed afterwards, it could be removed to detect those issues earlier.

Thanks for this amazing library btw! 👍
