### ISSUE TITLE
Unable to add a global option

### ISSUE THREAD

**Issue by samdidos** [Pop-Code/nestjs-console#346]
I want to create a global option to print the project version (defined in the `package.json` file) with flags `-v`, `-V` and `--version`

```bash
$ npm run cli -- -v
0.0.1
```

I use `@Console()` decorator at the root service of my CLI, and I was expecting to be able to add global options from the decorator parameter, but turns out it's a `CreateCommandOptions`, so I'm forced to create a new command to create options. I guess there is another way to do so but I don't find it in Wiki documentation.

P.S. : It could be a cool default feature to have version global option.

**Comment by Rmannn** [comment]
If the @Console is used without a name, that means you are registering a command on the root cli.

You can't define global options for the root cli using decorators. (the root cli is already defined)
You have to define options programmatically using the ConsoleService.

Inject the console service in your provider, then define an options on the rootCli.

```ts
import { ConsoleService } from 'nestjs-console';

@Injectable()
class MyService {
    constructor(console: ConsoleService){
        const rootCli = console.getRootCli();
        rootCli.option('-v,--version', 'The description of the option');
    }
} 
```

**However, a global option is not a good idea since you will have to handle this options in each command handler.**

Commander (npm) already provides a way to print the version.
See https://www.npmjs.com/package/commander#version-option.

```ts
import { ConsoleService } from 'nestjs-console';

@Injectable()
class MyService {
    constructor(console: ConsoleService){
        const rootCli = console.getRootCli();
        rootCli.version('0.0.1', '-v, --version', 'output the current version');
    }
} 
```

**Comment by samdidos** [comment]
Thank you! That solved it neatly :smile:
