### ISSUE TITLE
Any way to bind the cli to a running server?

### ISSUE THREAD

**Issue by DimosthenisK** [Pop-Code/nestjs-console#56]
I see in the docs that this requires an applicationInstance instead of a server - is it possible to modify it so that the cli binds to an existing server instance or creates it on initialization?

My use case is that I want to see currently connected clients (socketio) on demand from the CLI, something that seems impossible without attaching to the running instance.

**Comment by Rmannn** [comment]
You want the NestApplicationContext (created by cli) instance to become a NestApplication.

The problem is that once started, the app will be tied to the terrminal and you won't be able to interact with it.
The only thing that could be done this way is to start the server of the app or any other server. (dev servers etc, workers and other)

**In your case**, you should use the cli to connect to your socket.io server as a client.
You might create a dedicated room to monitor your connections between your server and your clients.
It's not required to have a server instance (NestApplication insteadof NestApplicationContext) to connect as a client.

However, to show you how to do if you need to have a NestApplication for any reason, you could do it by extending the BootstrapConsole Class and overriding the static createAppContext method to return a NestApplication.
That said, I will update the typing to do it in a more easy way.

```ts
// custom bootstrap.ts
import { NestFactory } from '@nestjs/core';
import { BootstrapConsole, BootstrapConsoleOptions } from './bootstrap';

export interface CustomBootstrapConsoleOptions extends BootstrapConsoleOptions {
    contextOptions?: NestApplicationOptions;
}

export class CustomBootstrapConsole extends BootstrapConsole {
    static createAppContext(options: BootstrapConsoleOptions) {
        return NestFactory.create(options.module, new ExpressAdapter(), options.contextOptions);
    }
}
```

Modify your console.ts
```ts
// console.ts
import { INestApplication } from '@nestjs/common';
import { CustomBootstrapConsole } from './bootstrap.app';
import { MyModule } from './module';

CustomBootstrapConsole.init({
    module: MyModule,
    withContainer: true // This is the key that will give you access to the app container from the service cli
}).then(({ app, boot }) => {
    // Here app is now a NestApplication.
    // we could start a server here, but it's not what we want to do, we will loose control as soon as the server started
    // X (app as INestApplication).listen(3000);
    boot(); // boot the cli
});
```
Then create a method in a service that will be binded to a cli command.
This cli command will start the server or whatever you want to.
```ts
// service.ts (imported in any module of your app)
import { Console, Command, ConsoleService } from 'nestjs-console'

@Console()
@Injectable()
export class AppManager {
    constructor(private consoleService: ConsoleService){}

    @Command({
        command: 'start',
        description: 'Start the application'
    })
    async start(name: string): void | Promise<void> {
        // access the app container (nestjs-console withContainer option must be true)
        const app = this.consoleService.getContainer();
        app.listen(3000);
    }
}
```

**Comment by Caperious** [comment]
@Rmannn I have a follow-up question. 

I have a similar use case, where I want the HTTP server and the CLI bound together, except I want to send the commands to the application via a cron job.

Is it possible to start the HTTP server via the console app, and then listen somehow to send commands to the CLI?

Also, the example above is a bit out of date, so I'm having trouble getting it to work.
