### ISSUE TITLE
What does this project do differently compared to nest-commander ? 

### ISSUE THREAD

**Issue by seyfer** [Pop-Code/nestjs-console#711]
https://docs.nestjs.com/recipes/nest-commander is mentioned in the Nest docs.

But this project, nestjs-console, has more stars. And I am confused, about which one to use.
There is a similar question in nest-commander repo about nestjs-console, about the difference.
And it was answered by the project author. 
https://github.com/jmcdo29/nest-commander/issues/10

Would be nice to get an answer here as well from @Rmannn.

**Comment by Rmannn** [comment]
Hi, 

This package was created long time ago before nest-commander.
I am still supporting it and updating it when required or asked. 

It was used and actively maintained in a production project and I think it is still used.

However I am not using nestjs anymore at work, so I may miss some new concepts from latest nestjs version.
I do not plan adding features except if someone submits a PR or want to become a maintainer.

As explained on the nest-commander issue you created, if you are looking for an easy and fast implementation of a cli you could try this package.

The first idea behind this tool was to proxy some of our services, that's why you can encapsulate more than one commands per class. 

Decorator is also a way to expose some of your service's methods to the cli. It's straightforward.

It seems that nest-commander is more restrictive with the implementation interface. Sometimes you need boundaries to write good code but this results in a more opinionated implementation.

If you need something more structured, where options are strongly typed maybe nest-commander is better.
I did not take the time to read the nest-commander code. So I may be wrong.

Nestjs console allows you to create nested cli, I am not sure you can do it with nest-commander. Again, I may be wrong.

**Comment by seyfer** [comment]
@Rmannn thank you for the answer and the package. 
This answer will be helpful for anyone choosing a cli package for NestJS.
